package org.appwork.update.exchange;

public enum ServerError {
    UNKNOWN_APP,
    UNKNOWN_BRANCH,
    DOWNLOADPACKAGE_VALIDATION_ERROR,
    DOWNLOADPACKAGE_VALIDATION_ERROR_INTERN,

    PKG_CREATE_HASHMISMATCH,
    INVALID_BRANCH

}
